services:
  - type: web
    name: hotel-luluah-derna
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: hotel-db
    databaseName: hotel_management
    user: hotel_user
    region: frankfurt
    plan: free
